server:
  port: 1980

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8
  messages:
    encoding: UTF-8
    basename: messages #默认
